{
 "title": "IAM User Detail",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Account", "query": { "query": "label_values(account_id)" } },
   { "name": "iam_user", "label": "IAM User", "query": { "query": "label_values(user)" } },
   { "name": "region", "query": { "query": "label_values(region)" } },
   { "name": "resource_id", "query": { "query": "label_values(resource)" } }
  ]
 },
 "panels": [
  {
   "title": "IAM User Resource Detail",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "IAM_USER_Resource_Cost_List{job=~\"IAM_User_Resource_List_Cost_eu-west-1|IAM_User_Resource_List_Cost_ap-southeast-1\", region=~\"$region\", user=\"$iam_user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Cost (Last 14 days)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "exampledb",
     "rawSql": "SELECT * FROM exampledb.user_cost_details where instance_id=${resource_id:doublequote}"
    }
   ]
  },
  {
   "title": "Total Services Cost of IAM User",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "IAM_USER_Total_Services_Cost_List {job=~\"IAM_User_Total_Services_Cost_List_eu-west-1|IAM_User_Total_Services_Cost_List_ap-southeast-1\", region=~\"$region\", user=\"$iam_user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IAM User Detail",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "IAM_Users{job=\"IAM_User_Details\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}