{
 "title": "Federated IAM User Cost",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Account_ID",
    "label": "Account ID",
    "query": {
     "query": "label_values(FED_USER_Resource_Cost_List,account_id)"
    }
   },
   {
    "name": "month",
    "label": "Month",
    "query": {
     "query": "label_values(FED_USER_Resource_Cost_List,month)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Spent on Federated IAM Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(FED_USER_Resource_Cost_List{account_id=~\".*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Fed Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (account_id) (FED_USER_Resource_Cost_List))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cost of all the Federated IAM User",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 10, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(account_id) (FED_USER_Resource_Cost_List{account_id=~\"$Account_ID\", month=~\"$month\"})",
     "legendFormat": "{{account_id}}"
    }
   ]
  },
  {
   "title": "Cost Split in AWS Services",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(resource) (sum without(region, resource_id, resource_name) (FED_USER_Resource_Cost_List{account_id=~\"$Account_ID\", month=~\"$month\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost by Month",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by(month) (FED_USER_Resource_Cost_List{month=~\"$month\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region wise Cost",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(region) (FED_USER_Resource_Cost_List{account_id=~\"$Account_ID\", month=~\"$month\"})",
     "legendFormat": "{{Region}}"
    }
   ]
  }
 ]
}