{
 "title": "IAM Roles",
 "time": { "from": "now", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Account",
    "query": {
     "query": "label_values(iam_role_all_account)"
    }
   },
   {
    "name": "Region",
    "query": {
     "query": "label_values(iam_role_all_region)"
    }
   },
   { "name": "IAMRole", "label": "IAM Role", "query": { "query": "label_values(iam_role_all)" } },
   {
    "name": "instance_id",
    "label": "Instance ID",
    "query": {
     "query": "label_values(iam_role_service_resource_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IAM Roles Detail",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "IAM_Role_All{job=\"IAM-roles-all\", iam_role_all_account=\"$Account\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IAM Roles Service Detail (Last 14 days)",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "IAM_Role_Service{job=\"IAM-roles-service-data\", iam_role_service_region=\"$Region\", iam_role_of_service=\"$IAMRole\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Cost (Last 14 days)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "exampledb",
     "rawSql": "SELECT * FROM exampledb.role_cost_details WHERE instance_id = ${instance_id:doublequote}"
    }
   ]
  },
  {
   "title": "Start / Stop Action",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": {
    "content": "<div id=\"table-data\">\n  {{#each data}}\n  <table>\n    <tr>\n      <td class=\"resourceid\">{{iam_role_service_resource_id}}</td>\n      <td>{{iam_role_service_cost}}</td>\n      <td class=\"status\"><button class=\"editbtn\" id=\"checking\" type=\"submit\" >{{iam_role_service_state}}</button></td>\n    </tr>\n  </table>\n  {{/each}}\n</div>"
   },
   "targets": [
    {
     "expr": "IAM_Role_Service{job=\"IAM-roles-service-data\", iam_role_service_region=\"$Region\", iam_role_of_service=\"$IAMRole\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}