{
 "title": "IAM Cost Further Breakdown",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "IAMRole",
    "query": {
     "query": "label_values(aws_total_cost_by_iam_role,role_arn)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total IAM Role Cost",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "aws_total_cost_by_iam_role", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lambda IAM Role Costs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "aws_lambda_cost_by_iam_role", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Clouddwatch IAM Role Costs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "aws_cloudwatch_cost_by_iam_role",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SNS IAM Roe Costs",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "aws_sns_cost_by_iam_role", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Breakdown for Specific IAM Role",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "aws_cloudwatch_cost_by_iam_role{role_arn=\"$IAMRole\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_lambda_cost_by_iam_role{role_arn=\"$IAMRole\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_sns_cost_by_iam_role{role_arn=\"$IAMRole\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}