{
 "title": "Dummy Data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Account", "label": "Account", "query": { "query": "label_values()" } },
   { "name": "Region", "label": "Region", "query": { "query": "label_values()" } },
   {
    "name": "Role",
    "label": "IAM Role",
    "query": {
     "query": "label_values(iam_role_resource_costs_testing,role_name)"
    }
   },
   {
    "name": "Service",
    "label": "Service",
    "query": {
     "query": "label_values(service_costs_testing{role_name=\"$Role\"},service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IAM Roles Detail",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "iam_role_resource_costs_testing{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services and Cost",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "service_costs_testing{role_name=\"$Role\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Detail",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "iam_role_resource_costs_testing{role_name=\"$Role\", service=\"$Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IAM Roles top 5 Resources for service",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(5, sum by(resource_name) (iam_role_resource_costs_testing{role_name=\"$Role\", service=\"$Service\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 most expensive resources",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(5, sum by(resource_name) (iam_role_resource_costs_testing{role_name=\"$Role\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start / Stop Action",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": {
    "content": "<div id=\"table-data\">\n  {{#each data}}\n  <table>\n    <tr>\n      <td class=\"resourceid\">{{iam_role_service_resource_id}}</td>\n      <td>{{iam_role_service_cost}}</td>\n      <td class=\"status\"><button class=\"editbtn\" id=\"checking\" type=\"submit\" >{{iam_role_service_state}}</button></td>\n    </tr>\n  </table>\n  {{/each}}\n</div>"
   },
   "targets": [
    {
     "expr": "IAM_Role_Service{job=\"IAM-roles-service-data\", iam_role_service_region=\"$Region\", iam_role_of_service=\"$IAMRole\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}