{
 "title": "Xc3 project  Dashboard",
 "time": { "from": "now", "to": "now" },
 "templating": {
  "list": [
   { "name": "Account", "query": { "query": "label_values(account_id)" } },
   { "name": "region", "query": { "query": "label_values(region)" } },
   {
    "name": "Project",
    "query": {
     "query": "label_values(project_spend_project)"
    }
   },
   { "name": "Month", "query": { "query": "label_values(month)" } }
  ]
 },
 "panels": [
  {
   "title": "Project Spend Cost ",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(5, sum(Project_Spend_Cost{job=\"Project-Spend-Cost\"}) by (project_spend_project))",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": " sum(Project_Spend_Cost{job=\"Project-Spend-Cost\"}) by (project_spend_project)",
     "legendFormat": "{{value}}"
    }
   ]
  },
  {
   "title": "Top 5 most expensive services ",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(5, Expensive_Services_Detail)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}