namespace = "xc3team12pradhumna"
region = "ap-southeast-2"
snsendpoint = "mail.nilanshu@gmail.com"
slack_webhook_url = "https://hooks.slack.com/services/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"
Owner = "X1"
Creator = "X1"
Project = "xc3"